### ISSUE TITLE
using LiteLLM ? 

### ISSUE THREAD

**Issue by ishaan-jaff** [vkehfdl1/vkehfdl1#1]
Hi @vkehfdl1 ,
Thanks for starring LiteLLM. Are you using [LiteLLM](https://github.com/BerriAI/litellm)? (if yes, how can we make it better for you)

**Comment by vkehfdl1** [comment]
Hi @ishaan-jaff 
I am not currently using LiteLLM. But I am interested in using it!

**Comment by ishaan-jaff** [comment]
@vkehfdl1 what problem are you hoping to solve using LiteLLM ? 

(sorry for contacting you here btw) did not know how else to
